import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils"
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs"
import { Metadata } from "next"
import { Geist_Mono, Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        fontMono.variable,
        "font-sans",
        inter.variable
      )}
    >
      <body className="h-screen overflow-hidden">
        <ClerkProvider>
          <ThemeProvider>
            <div className="flex h-screen flex-col">
              <header className="flex h-[4.5rem] shrink-0 items-center justify-end gap-4 border-b p-4">
                <SignedOut>
                  <>
                    <SignInButton />
                    <SignUpButton>
                      <button className="h-10 cursor-pointer rounded-full bg-purple-700 px-4 text-sm font-medium text-white sm:h-12 sm:px-5 sm:text-base">
                        Sign Up
                      </button>
                    </SignUpButton>
                  </>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                  {/* <SignOutButton /> */}
                </SignedIn>
              </header>
              <div className="min-h-0 flex-1 overflow-hidden">{children}</div>
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
